### ISSUE TITLE
It does not include first occurrence of pattern

### ISSUE THREAD

**Issue by codeparksoftware** [SergeyBarskiy/RecurrenceCalculator#3] opened 2019-12-31 06:13 UTC
Your code calculates next occurrence but no first...
 it should contain first occurrence date.

**Comment by SergeyBarskiy** [comment] 2019-12-31 06:32
Do you have an example to share?

**Comment by codeparksoftware** [comment] 2019-12-31 18:13
StartDate=12/31/2019
DayOfMonth=31
interval=1
Occurrences=10
MonthOfYear=12
RecurrenceType=YearInstance
Tuesday=true
![image](https://user-images.githubusercontent.com/14142585/71629977-c9791800-2c00-11ea-969f-dd34b15debf9.png)
It generates dates by starting next year.
I think the problem causes due to startdate and creationdate equals. when I set startdate as one day ago then there is no problem.
If creation time of day older than event time of day for the same date I agree it should not show. But if event time of day older than creation time of day it should show the start date as next occurrence.

**Comment by SergeyBarskiy** [comment] 2020-01-01 20:44
I do not see the behavior you describe.
Here is my test and it passes.  Could you provide similar test that fails to assist?

Thank you,

[TestMethod]
        public void Should_Generate_Yearly_Recurrences_With_End_Date_Same_Start_Date()
        {
            var recurrence = new AppointmentRecurrence
            {
                RecurrenceType = RecurrenceType.Yearly,
                Interval = 1,
                DayOfMonth = 31,
                MonthOfYear = 12,
                Sunday = true,
                Monday = true,
                Tuesday = true,
                Wednesday = true,
                Thursday = true,
                Friday = true,
                Saturday = true,
                StartDate = new DateTime(2019, 12, 31),
                Occurrences = 3
            };
            var occurrences = _calendarUtility.CalculateOccurrences(recurrence).ToList();
            Assert.AreEqual(3, occurrences.Count, "Should create 3 occurrences");
            Assert.AreEqual(new DateTime(2019, 12, 31), occurrences[0], "Date 1 should be correct");
            Assert.AreEqual(new DateTime(2020, 12, 31), occurrences[1], "Date 2 should be correct");
            Assert.AreEqual(new DateTime(2021, 12, 31), occurrences[2], "Date 3 should be correct");
        }

**Comment by SergeyBarskiy** [comment] 2020-01-01 21:29
Fixed in this PR: https://github.com/SergeyBarskiy/RecurrenceCalculator/pull/4.
The issue is that yearly recurrence looks at time of the start date instead of just date, like other recurrences.

**Comment by SergeyBarskiy** [comment] 2020-01-01 21:33
Version 1.0.4 has been published to NuGet.

**Closed by SergeyBarskiy** 2020-01-01 21:33 UTC
